### ISSUE TITLE
Marker API example error with multiple performance groups on KNL

### ISSUE THREAD

**Issue by chtlp** [RRZE-HPC/likwid#86]
Hi, I am trying out likwid Marker API on KNL. It works fine with one group, however fails with multiple groups, e.g.
```
root@xeonphi-li:/home/linpengt/workspace/likwid/examples# /usr/local/bin/likwid-perfctr -C 0-15 -g CLOCK -g DATA -m ./C-markerAPI

...
ERROR - [./src/includes/perfmon_knl.h:1084] MSR write operation failed - Invalid argument 
Thread 0 wakes up again
ERROR - [./src/includes/perfmon_knl.h:899] MSR write operation failed - Bad file descriptor 
```

And running with either `-g CLOCK` and `-g DATA` works fine. The complete error log is at
https://gist.github.com/chtlp/f07696bed5de65f977f264880674c22a
Could anyone give any pointers what might be the issue?

Thanks!

**Comment by TomTheBear** [comment]
LIKWID tried to write a read-only register. I fixed that in https://github.com/RRZE-HPC/likwid/commit/27654da21bd408833f1bcdf89fc2c69a1504a065 and https://github.com/RRZE-HPC/likwid/commit/0e69accc7ab3ca120a92d6d6d4beb80e83fd236a .
Moreover, I updated the C-markerAPI example to really measure multiple groups. Before the fix, it changes the groups but didn't measure them. https://github.com/RRZE-HPC/likwid/commit/8e1c6ff896e9fa5249db3c1aa046eab9b0d18c4c .

**Comment by chtlp** [comment]
Hi @TomTheBear , thanks for the quick response! I just pulled the new version, however the issue still occurred. Here is the new log (this time I tried only two cores):
https://gist.github.com/chtlp/d548e05c9d22204761fc96edf5607e40

Could you reproduce the error?

**Comment by TomTheBear** [comment]
Are you sure you called `make distclean` after you pulled the new version? With old versions I can reproduce the error but not with the latest version.

**Comment by chtlp** [comment]
Hi @TomTheBear, I just ran `make distclean` and tried it again. The number of errors have reduced to 2, so there seems to be some improvement, but the error still exists. See the full log here:
https://gist.github.com/chtlp/3b331aadba8006cbb00f10a7ea53b7a4

**Comment by TomTheBear** [comment]
Please run your test again with `-V 3` on commandline. The errors are still at the same point (`KNL_CHECK_CORE_OVERFLOW`) as before the fix. With -V 3 I can see whether it is the "overflow status" register or the the "clear overflow status" register. The "clear overflow status" was the one in the fix. It would be really strange when your system has neither of the overflow registers.

**Comment by chtlp** [comment]
Hi @TomTheBear, sure. See attached for the more verbose logs:
https://gist.github.com/chtlp/0d103b25a5155736b99639afb295a400

**Comment by TomTheBear** [comment]
Hi,
so the log reveals that LIKWID has problems writing register 0x38E (failure occurs twice):
```
Got error 'failed to read/write register' from access daemon writing reg 0x38E at CPU 0
MSR write operation failed - Invalid argument 
```
This is curious as the 0x38E register is a very common one (IA32_PERF_GLOBAL_STATUS). The interesting part is the second line where it documents a write attempt. The register is read-only, so we know the reason of the failure. But there is no write to that register in the code.

Can you try to read it using other tools, e.g. `rdmsr 0x38E` from the msr-tools package?

**Comment by chtlp** [comment]
Hi @TomTheBear,

Thanks for the detailed explanation. I can read it using `rdmsr`:
```
linpengt@xeonphi-li:~/workspace/cgt/likwid/examples$ sudo rdmsr 0x38E
0
```

**Comment by TomTheBear** [comment]
There is no write to that register, I rechecked it twice. There was a write before the fix but you pulled the latest version and made a `make distclean && make && sudo make install`, so you should have the fix compiled in and installed.

You can check that manually by looking in line 850 of `src/includes/perfmon_knl.h`. The `HPMwrite` function should get register `MSR_PERF_GLOBAL_OVF_CTRL` and not `MSR_PERF_GLOBAL_STATUS` as destination.

**Comment by chtlp** [comment]
Hi @TomTheBear, sorry for the trouble: I was using likwid in a submodule and didn't pull to the newest version correctly. Now it's working without errors. Thanks, please close the issue.
